# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 2

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 3

[[main]]
  name = "Accomplishments"
  url = "#accomplishments"
  weight = 4

# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 5
# 
# [[main]]
#   name = "Teaching"
#   url = "#teaching"
#   weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "Resume"
#    url = "static/files/Shreenath Iyer.pdf"
#    weight = 7

# [[main]]
#   name = "Publications"
#   url = "#publications_featured"
#   weight = 2

# [[main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 4
# 
# [[main]]
#   name = "Tutorials"
#   url = "/tutorial/"
#   weight = 5


